name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Unzip project
        run: |
          unzip jarvisfull.zip
          cp -r jarvis-full/* .

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Gradle Wrapper
        run: |
          chmod +x gradlew   # Даем права на выполнение gradlew
          ./gradlew wrapper  # Устанавливаем wrapper, если он не был распакован

      - name: Build APK
        run: ./gradlew assembleDebug --stacktrace 
